export default {
  SET_KEYWORDS: 'SET_KEYWORDS',
  SET_ONLY_TORRENTS_WITH_SEEDERS: 'SET_ONLY_TORRENTS_WITH_SEEDERS',
  ADD_TORRENT_TO_QUEUE: 'ADD_TORRENT_TO_QUEUE',
  REMOVE_TORRENT_FROM_QUEUE: 'REMOVE_TORRENT_FROM_QUEUE',
};
